name: Validate python code using black and ruff

on:
  pull_request:
    branches:
      - current
    paths:
      - '**/*.py'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  validate-python-code:
    # uses: vyos/.github/.github/workflows/assign-author.yml@feature/T6349-reusable-workflows
    uses: solvers-camp/.github/.github/workflows/validate-python-code.yml@main
    with:
      base_ref: 'current'
      head_ref: 'black_and_ruff'
    secrets: inherit
